function u = W_PART(sgn, fEND, fENDm1, SigmaEND, SigmaENDm1, KAPPAJm1, KAPPAJ, dz, ...
    coeff_1i_m_C0_m_2_d_3_d_dt, coeff_1i_m_C0_d_3_d_dt)

u = sgn * dz * ((-coeff_1i_m_C0_m_2_d_3_d_dt/KAPPAJ) * fEND ...
    + (-coeff_1i_m_C0_d_3_d_dt/KAPPAJ) * fENDm1...
    - KAPPAJm1/KAPPAJ*(2.0D0 * SigmaEND + SigmaENDm1));

% WL_PART = -dz * ((-coeff_1i_m_C0_m_2_d_3_d_dt) * field(1)...
%     + (-coeff_1i_m_C0_d_3_d_dt) * field(2)...
%     - (2.0D0 * Sigma0(IDX(step-1)) + Sigma1(IDX(step-1))));
% 
% 
% 
% WR_PART =  dz * ((-coeff_1i_m_C0_m_2_d_3_d_dt) * field(Nz)...
%     + (-coeff_1i_m_C0_d_3_d_dt) * field(Nzm1)...
%     - (2.0D0 * SigmaNz(IDX(step-1)) + SigmaNzm1(IDX(step-1))));
end